### ISSUE TITLE
Wrong Return defintion?

### ISSUE THREAD

**Issue by chf0x** [toolCHAINZ/jingle#10]
Good evening, sorry it is me again 
```
    Return {
        input: IndirectVarNode,
    },
```
I guess in this case input is again combination of input0 and input1? But according to the documentation input1 is optional

```
input0 		Varnode containing offset of next instruction.
[input1] 	Value returned from call (never present in raw p-code)
```
> If input1 is present it represents the value being returned by this operation. This is used by analysis algorithms to hold the value logically flowing back to the parent subroutine.

It seems with the current implementation, I am unable to get a returned a value/retrieve the offset of next instruction?

**Comment by toolCHAINZ** [comment]
The important thing to note here from the documentation is this:

> This instruction is semantically equivalent to the BRANCHIND instruction

If we look at BRANCHIND:

> The address to branch to is determined dynamically (at runtime) by examining the contents of the variable input0. As this instruction is currently defined, the variable input0 only contains the offset of the destination, and the address space is taken from the address associated with the branching instruction itself.

So, BRANCHIND, like RETURN, takes as input the location of a _pointer_ which contains the offset that is branched to, within the same space.

This is effectively indirect addressing just like load and store (but this time to compute a branch rather than to load or store data); so I used the same indirect type here to indicate that. I am adding in a fake "space id" varnode myself based on the space the instruction was read from:

```rust
input: IndirectVarNode {
                        pointer_location: VarNode::from(&value.inputs[0]),
                        access_size_bytes: value.space.getAddrSize() as usize,
                        pointer_space_index: value.space.getIndex() as usize,
                    },
```

So, initially kind of counter-intuitive but I think it's consistent and make sense.

And no need to apologize! I definitely appreciate the second set of eyes!

**Comment by chf0x** [comment]
Understood, thank you!
