### ISSUE TITLE
get_register_name out of bounds

### ISSUE THREAD

**Issue by chf0x** [toolCHAINZ/jingle#12]
Good evening! It seems there's an issue with the `get_register_name()` function. When I manually print all registers with their offsets, I can see that a register with an offset of 512 (CF) exists. However, when I try to retrieve its name using `get_register_name()`, I encounter an out-of-bounds error.

Here's the output I'm seeing:
```
Location: VarNode { space_index: 4, offset: 512, size: 1 }
byte index 5 is out of bounds of `X�`
```

Minimal example:

```rust
// Initialize sleigh for x86 first
let test = VarNode { space_index: 4, offset: 512, size: 1 };
let result = self.sleigh.get_register_name(test);
println!("Register name: {:?}", result);
// It crashes while trying to print some random unallocated memory
```

**Comment by toolCHAINZ** [comment]
This should be fixed as of d7ee2a1edffd0c97829f2daac217ca902b607030.

I never worked out what was actually happening here; I am pretty sure that I am using the C++ call correctly, but am getting back bad data. Not sure if this is a bug in sleigh or if there's some piece of initialization/filtering I should be doing in C++.

For now, I fixed this by just falling back on the `get_registers` call, since that one works, caching that info on the rust-side and then referencing that rather than using the other API.
