### ISSUE TITLE
Adding Windows support

### ISSUE THREAD

**Issue by dzonerzy** [toolCHAINZ/jingle#18]
Hi I tried building Jingle on windows but got multiple errors using MSVC toolchain, about missing headers and missing libraries, do you plan to add windows support without the use of MSYS?

**Comment by toolCHAINZ** [comment]
Hi! Yeah I tried to build on windows a while back and never got around to making it work because I don't work on windows generally and, at the time, I didn't have Linux CI set up and just didn't want to break anything.

As I recall I looked at this a little and it looks like sleigh requires some platform specific flags to be defined for windows builds to work. Presumably this would be doable with some simple build.rs changes.

I'd like this to work on windows (and get windows build CI set up) but don't have an immediate need for it myself. If you decide to give it a shot I'm happy to review PRs.

**Comment by toolCHAINZ** [comment]
I was working some on fixing some other issues and ended up digging around near this code. I _think_ that Windows builds are fixed as of #24.

I've not tried actually running it or testing it on windows, so I don't know if it _actually_ works. But it at least builds in CI.

**Comment by dzonerzy** [comment]
Thanks I'll try to compile as soon as possible and I'll be back to you

**Comment by toolCHAINZ** [comment]
I finally got around to ensuring the library can build on my local windows box. I'm going to go ahead and close this for now.
