### ISSUE TITLE
initialize_with_image/set_image with base_addr

### ISSUE THREAD

**Issue by chf0x** [toolCHAINZ/jingle#19]
Good evening! In the previous version, it was possible to set up `base_addr` in `Image` like this:

```rust
let mut image = Image::from(bytes);
image.sections[0].base_address = address as usize;
```

Is there a way to achieve similar functionality in the new version?

**Comment by toolCHAINZ** [comment]
Hmmm, so the sleigh loadimage abstraction does support specifying a base address. I hadn't touched that yet but it shouldn't be too bad to expose that. I'm actually likely to need that myself soon, so I'll probably look at this before too long. I'll let you know if/when I get around to it.

**Comment by chf0x** [comment]
I solved the issue locally by making the `ImageSectionIterator::new()` method public:

```rust
impl<'a> ImageSectionIterator<'a> {
    pub fn new<T: Iterator<Item = ImageSection<'a>> + 'a>(iter: T) -> Self {
        Self {
            iter: Box::new(iter),
        }
    }
}
```

Then, I implemented the `ImageProvider` trait for my local data type , which stores the address and permissions and provides them in get_section_info. Does this approach make sense, or would you prefer a cleaner solution?

**Comment by toolCHAINZ** [comment]
Reading through sleigh a little bit, it looks like there's nothing magic about the `adjustVma` routine in sleigh. It's just used as an API to allow programatically adjust the base address of a `LoadImage` whose source of truth is in C++.

As such, since the `RustLoadImage` pulls bytes from over the FFI, there's no actual reason to expose or use it; the type of solution you describe should be sufficient.

It migh make sense to expose a vma adjustment routine on the ImageProvider trait instead of doing it separately on implementing types.

**Comment by toolCHAINZ** [comment]
Actually, on second thought, this should probably be included directly on LoadedSleighContext and/or ImageFFI, as it's really independent of `ImageProvider`.

**Comment by toolCHAINZ** [comment]
I have added this in 4e4b842b53afb2b836a1d9f6c8ff75c578b1da05 and f97eacfc9a22b24202bf6d5064ad0a695cfae2ba.

This exposes an API to adjust the base address of an image. This should effect the reported addresses for sections, the bytes that come out of the read_bytes API, as well as the the instructions coming out of sleigh.

There was a bit of subtlety here, because of how sleigh handles relative jumps: they are resolved relative to the address sleigh is parsing.

So for instance `JUMP $+5` yields different p-code depending on the address it is at. I _think_ I've done it so that this works correctly.

For a usage example, see this unit test:

https://github.com/toolCHAINZ/jingle/blob/f97eacfc9a22b24202bf6d5064ad0a695cfae2ba/jingle_sleigh/src/context/loaded.rs#L244-L257
